name: GitHub Actions Build and Deploy Demo
# event
on:
  # type
  push:
    # condition
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # vm
    steps:
    - name: Checkout
      uses: actions/checkout@master # github actions to fetch code

    - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
      run: |
        mkdir build-test
        npm install
        npm run build

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.3 #https://github.com/marketplace/actions/deploy-to-github-pages
      with:
        # env variables
        # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
        # create one from profile and use it in repo
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: kj-test
        FOLDER: build-test
        BUILD_SCRIPT: npm install && npm run build